use_frameworks!

def default_pods
	pod 'Fabric'
	pod 'Crashlytics'
  pod 'Google-Mobile-Ads-SDK'
end

target 'Diploma-FREE' do
    default_pods
end

target 'Diploma-PRO' do
    default_pods
end

post_install do |installer|
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
   end
   end
 end
